# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  - master

steps:
- checkout: self
  persistCredentials: true
- bash: git checkout -b generated
  displayName: 'コード生成用ブランチの作成します'
- bash: docker pull tozastation/protocol_builder_golang
  displayName: 'Docker Imageを取得します'
- bash: docker exec -i $(docker run -v $PWD/grpc:/tmp/grpc -itd tozastation/protocol_builder_golang:latest) ash -c 'protoc -I $PROTO_PATH --plugin=$GRPC_PLUGIN_PATH --go_out=plugins=grpc:$GO_OUT_PATH $PROTO_PATH*.proto'
  displayName: 'Grpcコードを生成します'
- bash: git config --global user.email "DevOpsのメールアドレス"
  displayName: 'Emailを設定します'
- bash: git config --global user.name "DevOpsのユーザー名"
  displayName: 'UserNameを設定します'
- bash: git add .
  displayName: 'git管理対象に追加します'
- bash: git status
- bash: git commit -m "[Add] New Build File" || echo "Nothing Commit"
  displayName: '変更を保存します'
- bash: git push origin :generated; git push --set-upstream origin generated || echo "Nothing Update"
  displayName: '変更を通知します'